### ISSUE TITLE
Daten von Website ziehen

### ISSUE THREAD

**Issue by Amorgumena** [derRiesenOtter/BIGD#2]
Skript in Python schreiben, um Daten von Lebensmittelwarnung.de zu ziehen und überprüfen, ob die richtigen Daten gezogen werden. Zu ziehende Daten:

- Warnungstyp
- Produktbezeichnung
- Hersteller (am besten ohne Adresse und Website)
- Grund der Warnung
- Betroffene Länder
- Datum

Name der Datei: Lebensmittelwarnung.py

**Comment by derRiesenOtter** [comment]
Grundlegende Funktion ist implementiert. Eine Kürzung / Interpretation / Manipulation von den Daten der Website ist noch nicht implementiert.

**Comment by derRiesenOtter** [comment]
Tägliches Datenziehen und weiterleiten an Kafka muss noch erfolgen

**Comment by Amorgumena** [comment]
Datenziehen überarbeiten, sodass man sich einen Key vom letztgezogenen Eintrag merkt, z.B. Datum + Produktbezeichnung, und damit abgleicht, da die Daten nicht unbedingt regelmäßig kommen oder Wochenends gar nicht

**Comment by Amorgumena** [comment]
ID geht auch über URL-Adresse der Einträge
